name: Job Artifacts
on:
    push:
        branches:
            - master
jobs:
    Run_Code:
        runs-on: ubuntu-latest
        steps:
            - name: get code
              uses: actions/checkout@v4
            - name: install dependencies
              run: pip install flask
            - name: test code
              run: |
                  python3 test_app.py
                  python3 app.py &

    Get_Feedback:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout repo
            uses: actions/checkout@v4
          - name: Set up Python
            uses: actions/setup-python@v5
            with:
              python-version: '3.10'
          - name: Run Python script
            run: python generate_report.py
          - name: Upload report as artifact
            uses: actions/upload-artifact@v4
            with:
              name: report-artifact
              path: report.json

    Deploy:
        runs-on: ubuntu-latest
        steps:
            - name: get code
              uses: actions/checkout@v4
            - name: Deploy code
              run: echo "deploying..."

