name: Job Artifacts
on:
    push:
        branches:
            - master
jobs:
    Run_Code:
        runs-on: ubuntu-latest
        steps:
            - name: get code
              uses: actions/checkout@v4
            - name: install dependencies
              run: pip install flask
            - name: test code
              run: |
                  python3 test_app.py
                  python3 app.py &
    
    Get_Feedback:
        runs-on: ubuntu-latest
        steps:
            - name: get job info
              run: echo "${{ toJSON(github) }}"
            - name: push job info into Artifacts folder
              uses: actions/download-artifact@v4
              with: 
                name: get job info
                path: Artifacts_folder/artifacts.txt
    
    Deploy:
        runs-on: ubuntu-latest
        steps:
            - name: get code
              uses: actions/checkout@v4
            - name: Deploy code
              run: echo "deploying..."

