name: Job Artifacts
on:
    push:
        branches:
            - master
jobs:
    Run_Code:
        runs-on: ubuntu-latest
        steps:
            - name: get code
              uses: actions/checkout@v4
            - name: cache dependencies
              uses: actions/cache@v4
              with:
                path: ~/.cache/pip
                key: ${{ hashFiles('requirements.txt') }}
            - name: install dependencies
              run: pip install -r requirements.txt
            - name: test code
              run: python3 app.py &

    Get_Feedback:
        needs: Run_Code
        runs-on: ubuntu-latest
        steps:
          - name: Checkout repo
            uses: actions/checkout@v4
          - name: Set up Python
            uses: actions/setup-python@v5
            with:
              python-version: '3.10'
          - name: cache dependencies
            uses: actions/cache@v4
            with:
              path: ~/.cache/pip
              key: ${{ hashFiles('requirements.txt') }}
          - name: Run Python script
            run: python generate_report.py
          - name: Upload report as artifact
            uses: actions/upload-artifact@v4
            with:
              name: report-artifact
              path: report.json

    Deploy:
        needs: Get_Feedback
        runs-on: ubuntu-latest
        steps:
            - name: get code
              uses: actions/checkout@v4
            - name: cache dependencies
              uses: actions/cache@v4
              with:
                path: ~/.cache/pip
                key: ${{ hashFiles('requirements.txt') }}
            - name: get buils artifacts
              uses: actions/download-artifact@v4
              with:
                name: report-artifact
            - name: output downloads
              run: ls
              

